import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  container: {backgroundColor: '#afeeee'},
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    padding: 20,
    color: '#4E4FEB',
    textAlign: 'center',
  },
  subHeader: {
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 20,
    marginTop: 10,
    marginBottom: 5,
    color: '#333',
  },
  categoryScroll: {paddingLeft: 20},
  categoryItem: {
    backgroundColor: '#9370db',
    paddingVertical: 8,
    paddingHorizontal: 15,
    width: 100,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    marginRight: 10,
  },
  categoryText: {color: 'white', fontWeight: '600'},
  listContainer: {paddingHorizontal: 20, paddingTop: 10, paddingBottom: 20},
  productCard: {
    backgroundColor: 'white',
    padding: 18,
    borderRadius: 12,
    marginBottom: 12,
    elevation: 4,
  },
  productName: {fontSize: 20, fontWeight: 'bold', color: '#2c2c54'},
  productCategory: {fontSize: 14, color: '#999', marginVertical: 4},
  productPrice: {fontSize: 16, color: '#4E4FEB', fontWeight: '600'},
  modalContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  modalContent: {
    backgroundColor: 'white',
    width: 300,
    padding: 25,
    borderRadius: 12,
    alignItems: 'center',
    height: '40%',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#4E4FEB',
  },
  modalText: {fontSize: 16, marginVertical: 5, color: '#444'},
  closeButton: {
    marginTop: 15,
    backgroundColor: '#4E4FEB',
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 8,
  },
  closeButtonText: {color: 'white', fontWeight: 'bold'},
});
